name: Mahjong
on:
  workflow_dispatch:
  schedule:
    # 定期実行する時間
    - cron: '0 12 * * *'
env:
  API_KEY: ${{ secrets.API_KEY }}
  API_SECRET: ${{ secrets.API_SECRET }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
  IMGUR: ${{ secrets.IMGUR }}
  IFTTT: ${{ secrets.IFTTT }}

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: |
          echo "::group::pip install --upgrade pip"
          python -m pip install --upgrade pip==23.0
          pip install python-dotenv==0.21.1
          pip install tweepy==4.12.1
          pip install Pillow==9.4.0
          echo "::endgroup::"
          python Mahjong.py
      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v1
